In [2]:
import fastai
from fastai.tabular import *
import pandas as pd

In [3]:
df = pd.read_csv('../input/marketingrar/marketing.csv')
df.head()

,Date,Week,Week_ID,Month,Month_ID,Year,Day_Name,Visitors,Revenue,Marketing Spend,Promo
0,09/11/2020,46,34,11,11,2020,Monday,707,465,651.375,No Promo
1,10/11/2020,46,34,11,11,2020,Tuesday,1455,10386,1298.250,Promotion Red
2,11/11/2020,46,34,11,11,2020,Wednesday,1520,12475,1559.375,Promotion Blue
3,12/11/2020,46,34,11,11,2020,Thursday,1726,11712,1801.750,No Promo
4,13/11/2020,46,34,11,11,2020,Friday,2134,10000,2614.500,No Promo

In [4]:
df.dtypes

Date                object
Week                 int64
Week_ID              int64
Month                int64
Month_ID             int64
Year                 int64
Day_Name            object
Visitors             int64
Revenue              int64
Marketing Spend    float64
Promo               object
dtype: object

In [11]:
df.shape

(182, 11)

In [8]:
dep_var = 'Visitors'
cat_names = ['Date','Day_Name','Promo']
cont_names = ['Week','Month','Year','Revenue','Marketing Spend']
procs = [FillMissing, Categorify, Normalize]

In [14]:
data = (TabularList.from_df(df, cat_names=cat_names, cont_names=cont_names, procs=procs)
       .split_by_idx(valid_idx=())
       .label_from_df(cols=dep_var)
       .databunch())

In [15]:
data.show_batch()

In [20]:
learn = tabular_learner(data, layers=[200,100], metrics=accuracy)
learn.fit_one_cycle(30, 1e-2)
learn.save('mini_train')

In [22]:
learn.show_results()

NameError: name 'learner' is not defined